/*
 * ValueSpecificationAction.h
 *
 *  Created on: 17.08.2023
 *      Author: maha6913
 */

#ifndef FUML_SYNTAX_ACTIONS_VALUESPECIFICATIONACTION_H_
#define FUML_SYNTAX_ACTIONS_VALUESPECIFICATIONACTION_H_





#endif /* FUML_SYNTAX_ACTIONS_VALUESPECIFICATIONACTION_H_ */
