/*
 * LiteralUnlimitedNaturalEvaluation.h
 *
 *  Created on: 21.08.2023
 *      Author: Maximilian
 */

#ifndef FUML_SEMANTICS_VALUES_LITERALUNLIMITEDNATURALEVALUATION_H_
#define FUML_SEMANTICS_VALUES_LITERALUNLIMITEDNATURALEVALUATION_H_





#endif /* FUML_SEMANTICS_VALUES_LITERALUNLIMITEDNATURALEVALUATION_H_ */
