/*
 * LiteralStringEvaluation.h
 *
 *  Created on: 21.08.2023
 *      Author: Maximilian
 */

#ifndef FUML_SEMANTICS_VALUES_LITERALSTRINGEVALUATION_H_
#define FUML_SEMANTICS_VALUES_LITERALSTRINGEVALUATION_H_





#endif /* FUML_SEMANTICS_VALUES_LITERALSTRINGEVALUATION_H_ */
