/*
 * CompoundValue.h
 *
 *  Created on: 22.08.2023
 *      Author: maha6913
 */

#ifndef FUML_SEMANTICS_SIMPLESCLASSIFIERS_COMPOUNDVALUE_H_
#define FUML_SEMANTICS_SIMPLESCLASSIFIERS_COMPOUNDVALUE_H_





#endif /* FUML_SEMANTICS_SIMPLESCLASSIFIERS_COMPOUNDVALUE_H_ */
