/*
 * MultipleDelegation_SameConnector_P_PWP_SignalModel.h
 * 
 * Auto-generated file
 */

#ifndef MULTIPLEDELEGATION_SAMECONNECTOR_P_PWP_SIGNAL_MODEL_H
#define MULTIPLEDELEGATION_SAMECONNECTOR_P_PWP_SIGNAL_MODEL_H

#include <uml/fwd.h>
#include <utils/environment/InMemoryModel.h>

/* Start of user code : User-defined includes and forward declarations
 * This section may be used for includes and forward declarations.
 * It will not be overwritten by future generation processes.
 */

/*
 * End of user code
 */

namespace MultipleDelegation_SameConnector_P_PWP_Signal
{
	class MultipleDelegation_SameConnector_P_PWP_SignalModel : public uml::environment::InMemoryModel
	{
		public:
		/*
		 * Model MultipleDelegation_SameConnector_P_PWP_Signal
		 */
		PackagePtr MultipleDelegation_SameConnector_P_PWP_Signal = nullptr;
			Class_Ptr MultipleDelegation_SameConnector_P_PWP_Signal_Tester = nullptr;
				GeneralizationPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_Generalization0 = nullptr;
				ActivityPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow1 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow1_LiteralBoolean2 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow1_LiteralInteger3 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow4 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow4_LiteralBoolean5 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow4_LiteralInteger6 = nullptr;
					ReadStructuralFeatureActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_a_b = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_a_b_object = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_a_b_object_LiteralInteger7 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_a_b_object_LiteralUnlimitedNatural8 = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_a_b_result = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_a_b_result_LiteralInteger9 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_a_b_result_LiteralUnlimitedNatural10 = nullptr;
					OpaqueBehaviorPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_testP = nullptr;
						ParameterPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_testP_p = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow11 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow11_LiteralBoolean12 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow11_LiteralInteger13 = nullptr;
					ReadSelfActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_this = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_this_result = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_this_result_LiteralUnlimitedNatural14 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_this_result_LiteralInteger15 = nullptr;
					ReadStructuralFeatureActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_this_c = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_this_c_result = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_this_c_result_LiteralUnlimitedNatural16 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_this_c_result_LiteralInteger17 = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_this_c_object = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_this_c_object_LiteralInteger18 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_this_c_object_LiteralUnlimitedNatural19 = nullptr;
					CallBehaviorActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Call_testP = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Call_testP_p = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Call_testP_p_LiteralInteger20 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Call_testP_p_LiteralInteger21 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Call_testP_p_LiteralUnlimitedNatural22 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow23 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow23_LiteralBoolean24 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow23_LiteralInteger25 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow26 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow26_LiteralBoolean27 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_ObjectFlow26_LiteralInteger28 = nullptr;
					ReadStructuralFeatureActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_b_p = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_b_p_object = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_b_p_object_LiteralInteger29 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_b_p_object_LiteralUnlimitedNatural30 = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_b_p_result = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_b_p_result_LiteralInteger31 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_b_p_result_LiteralUnlimitedNatural32 = nullptr;
					ReadStructuralFeatureActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_c_a_ = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_c_a__result = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_c_a__result_LiteralInteger33 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_c_a__result_LiteralUnlimitedNatural34 = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_c_a__object = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_c_a__object_LiteralUnlimitedNatural35 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_testActivity_Read_c_a__object_LiteralInteger36 = nullptr;
				OperationPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_Tester_Tester = nullptr;
					ParameterPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_Tester_Tester_result = nullptr;
				ActivityPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior = nullptr;
					ReadStructuralFeatureActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_c_p = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_c_p_object = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_c_p_object_LiteralInteger37 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_c_p_object_LiteralUnlimitedNatural38 = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_c_p_result = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_c_p_result_LiteralUnlimitedNatural39 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_c_p_result_LiteralInteger40 = nullptr;
					AcceptEventActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_3 = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_3_result = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_3_result_LiteralInteger41 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_3_result_LiteralUnlimitedNatural42 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_3_result_LiteralInteger43 = nullptr;
						TriggerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_3_Trigger44 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow45 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow45_LiteralBoolean46 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow45_LiteralInteger47 = nullptr;
					ControlFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ControlFlow48 = nullptr;
					AcceptEventActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Start = nullptr;
						TriggerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Start_Trigger49 = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Start_result = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Start_result_LiteralInteger50 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Start_result_LiteralUnlimitedNatural51 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Start_result_LiteralInteger52 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow53 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow53_LiteralInteger54 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow53_LiteralBoolean55 = nullptr;
					AcceptEventActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_4 = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_4_result = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_4_result_LiteralUnlimitedNatural56 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_4_result_LiteralInteger57 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_4_result_LiteralInteger58 = nullptr;
						TriggerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_4_Trigger59 = nullptr;
					ValueSpecificationActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Value_4 = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Value_4_result = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Value_4_result_LiteralInteger60 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Value_4_result_LiteralUnlimitedNatural61 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Value_4_LiteralInteger62 = nullptr;
					ControlFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ControlFlow63 = nullptr;
					CallOperationActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Call_test_ = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Call_test__target = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Call_test__target_LiteralInteger64 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Call_test__target_LiteralUnlimitedNatural65 = nullptr;
					ControlFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ControlFlow66 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow67 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow67_LiteralInteger68 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow67_LiteralBoolean69 = nullptr;
					ControlFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ControlFlow70 = nullptr;
					AcceptEventActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_1 = nullptr;
						TriggerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_1_Trigger71 = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_1_result = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_1_result_LiteralUnlimitedNatural72 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_1_result_LiteralInteger73 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_1_result_LiteralInteger74 = nullptr;
					ForkNodePtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Fork_this = nullptr;
					ControlFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ControlFlow75 = nullptr;
					ReadStructuralFeatureActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_this_c = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_this_c_result = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_this_c_result_LiteralUnlimitedNatural76 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_this_c_result_LiteralInteger77 = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_this_c_object = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_this_c_object_LiteralUnlimitedNatural78 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Read_this_c_object_LiteralInteger79 = nullptr;
					SendSignalActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Send_S = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Send_S_t = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Send_S_t_LiteralInteger80 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Send_S_t_LiteralUnlimitedNatural81 = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Send_S_target = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Send_S_target_LiteralUnlimitedNatural82 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Send_S_target_LiteralInteger83 = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Send_S_v = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Send_S_v_LiteralInteger84 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Send_S_v_LiteralUnlimitedNatural85 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow86 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow86_LiteralInteger87 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow86_LiteralBoolean88 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow89 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow89_LiteralBoolean90 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow89_LiteralInteger91 = nullptr;
					AcceptEventActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_2 = nullptr;
						TriggerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_2_Trigger92 = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_2_result = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_2_result_LiteralUnlimitedNatural93 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_2_result_LiteralInteger94 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_Accept_Continue_2_result_LiteralInteger95 = nullptr;
					ReadSelfActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_this = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_this_result = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_this_result_LiteralInteger96 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_this_result_LiteralUnlimitedNatural97 = nullptr;
					ControlFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ControlFlow98 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow99 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow99_LiteralBoolean100 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow99_LiteralInteger101 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow102 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow102_LiteralBoolean103 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_TesterClassifierBehavior_ObjectFlow102_LiteralInteger104 = nullptr;
				OperationPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_test = nullptr;
				PropertyPtr MultipleDelegation_SameConnector_P_PWP_Signal_Tester_c = nullptr;
			SignalEventPtr MultipleDelegation_SameConnector_P_PWP_Signal_ContinueEvent = nullptr;
			SignalEventPtr MultipleDelegation_SameConnector_P_PWP_Signal_StartEvent = nullptr;
			AssociationPtr MultipleDelegation_SameConnector_P_PWP_Signal_U = nullptr;
				PropertyPtr MultipleDelegation_SameConnector_P_PWP_Signal_U_x = nullptr;
					LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_U_x_LiteralUnlimitedNatural105 = nullptr;
					LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_U_x_LiteralInteger106 = nullptr;
				PropertyPtr MultipleDelegation_SameConnector_P_PWP_Signal_U_y = nullptr;
					LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_U_y_LiteralInteger107 = nullptr;
					LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_U_y_LiteralUnlimitedNatural108 = nullptr;
			Class_Ptr MultipleDelegation_SameConnector_P_PWP_Signal_C = nullptr;
				ConnectorPtr MultipleDelegation_SameConnector_P_PWP_Signal_C_u = nullptr;
					ConnectorEndPtr MultipleDelegation_SameConnector_P_PWP_Signal_C_u_ConnectorEnd109 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_C_u_ConnectorEnd109_LiteralInteger110 = nullptr;
						LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_C_u_ConnectorEnd109_LiteralUnlimitedNatural111 = nullptr;
					ConnectorEndPtr MultipleDelegation_SameConnector_P_PWP_Signal_C_u_ConnectorEnd112 = nullptr;
						LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_C_u_ConnectorEnd112_LiteralUnlimitedNatural113 = nullptr;
				PropertyPtr MultipleDelegation_SameConnector_P_PWP_Signal_C_a = nullptr;
					LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_C_a_LiteralUnlimitedNatural114 = nullptr;
					LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_C_a_LiteralInteger115 = nullptr;
				PortPtr MultipleDelegation_SameConnector_P_PWP_Signal_C_p = nullptr;
			InterfacePtr MultipleDelegation_SameConnector_P_PWP_Signal_I = nullptr;
				ReceptionPtr MultipleDelegation_SameConnector_P_PWP_Signal_I_S = nullptr;
			Class_Ptr MultipleDelegation_SameConnector_P_PWP_Signal_B = nullptr;
				ActivityPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow116 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow116_LiteralBoolean117 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow116_LiteralInteger118 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow119 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow119_LiteralBoolean120 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow119_LiteralInteger121 = nullptr;
					ControlFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ControlFlow122 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow123 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow123_LiteralInteger124 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow123_LiteralBoolean125 = nullptr;
					AcceptEventActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Accept_S = nullptr;
						TriggerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Accept_S_Trigger126 = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Accept_S_s = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Accept_S_s_LiteralUnlimitedNatural127 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Accept_S_s_LiteralInteger128 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Accept_S_s_LiteralInteger129 = nullptr;
					AddStructuralFeatureValueActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Set_this_p = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Set_this_p_result = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Set_this_p_result_LiteralUnlimitedNatural130 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Set_this_p_result_LiteralInteger131 = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Set_this_p_object = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Set_this_p_object_LiteralInteger132 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Set_this_p_object_LiteralUnlimitedNatural133 = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Set_this_p_value = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Set_this_p_value_LiteralInteger134 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Set_this_p_value_LiteralUnlimitedNatural135 = nullptr;
					SendSignalActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Send_Continue = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Send_Continue_target = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Send_Continue_target_LiteralUnlimitedNatural136 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Send_Continue_target_LiteralInteger137 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow138 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow138_LiteralBoolean139 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow138_LiteralInteger140 = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow141 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow141_LiteralBoolean142 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow141_LiteralInteger143 = nullptr;
					ReadStructuralFeatureActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_v = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_v_result = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_v_result_LiteralInteger144 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_v_result_LiteralUnlimitedNatural145 = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_v_object = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_v_object_LiteralInteger146 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_v_object_LiteralUnlimitedNatural147 = nullptr;
					ReadStructuralFeatureActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_t = nullptr;
						InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_t_object = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_t_object_LiteralInteger148 = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_t_object_LiteralUnlimitedNatural149 = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_t_result = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_t_result_LiteralUnlimitedNatural150 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Read_s_t_result_LiteralInteger151 = nullptr;
					ReadSelfActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_this = nullptr;
						OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_this_result = nullptr;
							LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_this_result_LiteralUnlimitedNatural152 = nullptr;
							LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_this_result_LiteralInteger153 = nullptr;
					ForkNodePtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_Fork_s = nullptr;
					ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow154 = nullptr;
						LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow154_LiteralBoolean155 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_BClassifierBehavior_ObjectFlow154_LiteralInteger156 = nullptr;
				InterfaceRealizationPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_IRealization = nullptr;
				OperationPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_B_B = nullptr;
					ParameterPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_B_B_result = nullptr;
				PropertyPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_p = nullptr;
				ReceptionPtr MultipleDelegation_SameConnector_P_PWP_Signal_B_S = nullptr;
			SignalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Continue = nullptr;
			Class_Ptr MultipleDelegation_SameConnector_P_PWP_Signal_A = nullptr;
				PortPtr MultipleDelegation_SameConnector_P_PWP_Signal_A_q = nullptr;
				ConnectorPtr MultipleDelegation_SameConnector_P_PWP_Signal_A_r = nullptr;
					ConnectorEndPtr MultipleDelegation_SameConnector_P_PWP_Signal_A_r_ConnectorEnd157 = nullptr;
						LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_A_r_ConnectorEnd157_LiteralUnlimitedNatural158 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_A_r_ConnectorEnd157_LiteralInteger159 = nullptr;
					ConnectorEndPtr MultipleDelegation_SameConnector_P_PWP_Signal_A_r_ConnectorEnd160 = nullptr;
						LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_A_r_ConnectorEnd160_LiteralUnlimitedNatural161 = nullptr;
				OperationPtr MultipleDelegation_SameConnector_P_PWP_Signal_A_A_A = nullptr;
					ParameterPtr MultipleDelegation_SameConnector_P_PWP_Signal_A_A_A_result = nullptr;
				PropertyPtr MultipleDelegation_SameConnector_P_PWP_Signal_A_b = nullptr;
					LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_A_b_LiteralInteger162 = nullptr;
					LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_A_b_LiteralUnlimitedNatural163 = nullptr;
			AssociationPtr MultipleDelegation_SameConnector_P_PWP_Signal_R = nullptr;
				PropertyPtr MultipleDelegation_SameConnector_P_PWP_Signal_R_x = nullptr;
					LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_R_x_LiteralUnlimitedNatural164 = nullptr;
					LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_R_x_LiteralInteger165 = nullptr;
				PropertyPtr MultipleDelegation_SameConnector_P_PWP_Signal_R_y = nullptr;
					LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_R_y_LiteralInteger166 = nullptr;
					LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_R_y_LiteralUnlimitedNatural167 = nullptr;
			SignalPtr MultipleDelegation_SameConnector_P_PWP_Signal_S = nullptr;
				PropertyPtr MultipleDelegation_SameConnector_P_PWP_Signal_S_v = nullptr;
				PropertyPtr MultipleDelegation_SameConnector_P_PWP_Signal_S_t = nullptr;
			SignalEventPtr MultipleDelegation_SameConnector_P_PWP_Signal_SEvent = nullptr;
			Class_Ptr MultipleDelegation_SameConnector_P_PWP_Signal_IImpl = nullptr;
				InterfaceRealizationPtr MultipleDelegation_SameConnector_P_PWP_Signal_IImpl_IRealization = nullptr;
				ReceptionPtr MultipleDelegation_SameConnector_P_PWP_Signal_IImpl_S = nullptr;
			Class_Ptr MultipleDelegation_SameConnector_P_PWP_Signal_AbstractTester = nullptr;
				ReceptionPtr MultipleDelegation_SameConnector_P_PWP_Signal_AbstractTester_Start = nullptr;
				OperationPtr MultipleDelegation_SameConnector_P_PWP_Signal_AbstractTester_test = nullptr;
				ReceptionPtr MultipleDelegation_SameConnector_P_PWP_Signal_AbstractTester_Continue = nullptr;
			ActivityPtr MultipleDelegation_SameConnector_P_PWP_Signal_main = nullptr;
				ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ObjectFlow168 = nullptr;
					LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ObjectFlow168_LiteralInteger169 = nullptr;
					LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ObjectFlow168_LiteralBoolean170 = nullptr;
				ForkNodePtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Fork_Tester = nullptr;
				ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ObjectFlow171 = nullptr;
					LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ObjectFlow171_LiteralInteger172 = nullptr;
					LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ObjectFlow171_LiteralBoolean173 = nullptr;
				CallOperationActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Tester_ = nullptr;
					InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Tester__target = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Tester__target_LiteralInteger174 = nullptr;
						LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Tester__target_LiteralUnlimitedNatural175 = nullptr;
					OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Tester__result = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Tester__result_LiteralInteger176 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Tester__result_LiteralInteger177 = nullptr;
						LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Tester__result_LiteralUnlimitedNatural178 = nullptr;
				StartObjectBehaviorActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Start_Tester = nullptr;
					InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Start_Tester_object = nullptr;
						LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Start_Tester_object_LiteralUnlimitedNatural179 = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Start_Tester_object_LiteralInteger180 = nullptr;
				ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ObjectFlow181 = nullptr;
					LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ObjectFlow181_LiteralBoolean182 = nullptr;
					LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ObjectFlow181_LiteralInteger183 = nullptr;
				CreateObjectActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Create_Tester = nullptr;
					OutputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Create_Tester_result = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Create_Tester_result_LiteralInteger184 = nullptr;
						LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Create_Tester_result_LiteralUnlimitedNatural185 = nullptr;
				SendSignalActionPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Send_Start = nullptr;
					InputPinPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Send_Start_target = nullptr;
						LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Send_Start_target_LiteralInteger186 = nullptr;
						LiteralUnlimitedNaturalPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_Send_Start_target_LiteralUnlimitedNatural187 = nullptr;
				ObjectFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ObjectFlow188 = nullptr;
					LiteralIntegerPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ObjectFlow188_LiteralInteger189 = nullptr;
					LiteralBooleanPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ObjectFlow188_LiteralBoolean190 = nullptr;
				ControlFlowPtr MultipleDelegation_SameConnector_P_PWP_Signal_main_ControlFlow191 = nullptr;
			SignalPtr MultipleDelegation_SameConnector_P_PWP_Signal_Start = nullptr;

		public:
			virtual ~MultipleDelegation_SameConnector_P_PWP_SignalModel();
			static const std::shared_ptr<MultipleDelegation_SameConnector_P_PWP_SignalModel>& Instance();

		private:
			MultipleDelegation_SameConnector_P_PWP_SignalModel();
			void initializeInMemoryModel();

		/* Start of user code : User-defined members
		 * This section may be used for user-defined members.
		 * It will not be overwritten by future generation processes.
		 */

		/*
 		 * End of user code
		 */
	};
}

#endif /* MULTIPLEDELEGATION_SAMECONNECTOR_P_PWP_SIGNAL_MODEL_H */
